# TYPE OF ARRAYS
# 1. ONE DIAMENTIONAL ARRAY [1,2,3,4,5]
# 2. TWO DIAMENTIONAL ARRAY []
# 3. MULTY DIAMENTIONAL ARRAY 3D 4D 5D AS NAME DIFINES HERE WE HAVE ARRAYS LIKE 3X3X2 4X5X5  TOTALLY MULTY DIANMENTIONAL

import numpy as np 

# ONE DIAMENTIONAL ARRAY
arr_1d = np.array({1,2,3,4,5})
print("ONE DIAMENTIONAL ARRAY :-- ")
print(arr_1d) 
print()
print()

# TWO DIAMENTIONAL ARRAY
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("TWO DIAMENTIONAL ARRAY :-- ")
print(arr_2d)
print()
print()


# MULTY DIAMENTIONAL ARRAY 
arr_3d = np.array([[2, 3, 4,],
                   [2, 2, 4],
                   [3, 2, 3]])
print("MULTY DIAMENTIONAL ARRAY JUST A EXAMPLE!")
print(arr_3d)